name: Deploy to Server

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ssh deploy
        uses: JimCronqvist/action-ssh@master
        env:
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          hosts: 'root@${{ secrets.REMOTE_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command: |
            cd ~/BiBiT
            git reset --hard
            git pull origin master
            pipenv install --system
            pm2 stop BiBiT
            pm2 del BiBiT
            rm .env
            echo "export TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN" >> .env
            echo "export TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET" >> .env
            echo "export TWITTER_API_KEY=$TWITTER_API_KEY" >> .env
            echo "export TWITTER_API_SECRET_KEY=$TWITTER_API_SECRET_KEY" >> .env
            echo "export DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL" >> .env
            source ~/.bashrc
            pm2 start main.py --interpreter python3 --name "BiBiT" --ignore-watch ./data


